@extends('layouts.app')

@section('content')
<div class="container py-4">
    <h1 class="mb-4 text-center">Manage Reports</h1>

    {{-- Export Buttons --}}
    <div class="d-flex justify-content-end mb-3 gap-2">
        <a href="{{ route('admin.exportReports', 'pdf') }}" class="btn btn-outline-primary">Export as PDF</a>
        <a href="{{ route('admin.exportReports', 'csv') }}" class="btn btn-outline-secondary">Export as CSV</a>
    </div>

    {{-- Reports Table --}}
    @if($reports->isEmpty())
        <div class="alert alert-info text-center">No reports available.</div>
    @else
        <div class="table-responsive">
            <table class="table table-bordered table-hover align-middle">
                <thead class="table-light">
                    <tr>
                        <th>Title</th>
                        <th>Status</th>
                        <th>Generated By</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reports as $report)
                        <tr>
                            <td>{{ $report->title }}</td>
                            <td>
                                @if($report->status === 'approved')
                                    <span class="badge bg-success">Approved</span>
                                @elseif($report->status === 'rejected')
                                    <span class="badge bg-danger">Rejected</span>
                                @else
                                    <span class="badge bg-warning text-dark">Pending</span>
                                @endif
                            </td>
                            <td>{{ optional($report->generatedBy)->name ?? 'N/A' }}</td>
                            <td>
                                @if($report->status === 'pending')
                                    <div class="d-flex gap-2">
                                        <form action="{{ route('admin.approveReport', $report->id) }}" method="POST">
                                            @csrf
                                            <button class="btn btn-sm btn-success">Approve</button>
                                        </form>

                                        <form action="{{ route('admin.rejectReport', $report->id) }}" method="POST" onsubmit="return confirm('Are you sure you want to reject this report?');">
                                            @csrf
                                            <button class="btn btn-sm btn-danger">Reject</button>
                                        </form>
                                    </div>
                                @else
                                    <span class="text-muted">No actions available</span>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @endif
</div>
@endsection
